import { Contract } from './types';

export const MOCK_CONTRACTS: Contract[] = [
  {
    id: 'CON-001',
    title: 'Software License Agreement',
    party: 'AmaliTech Ghana',
    value: 450000,
    currency: 'GHS',
    startDate: '2024-01-15',
    endDate: '2025-01-14',
    status: 'Active',
    category: 'IT Services',
    description: 'Annual enterprise license for core infrastructure software.',
    owner: 'Abena Osei',
    lastModified: '2024-03-10',
    authorId: 'mock-user',
  },
  {
    id: 'CON-002',
    title: 'Office Lease - Kumasi',
    party: 'Consar Limited',
    value: 1200000,
    currency: 'GHS',
    startDate: '2023-06-01',
    endDate: '2026-05-31',
    status: 'Active',
    category: 'Real Estate',
    description: 'Main office space lease agreement for floors 4-6.',
    owner: 'Kwame Mensah',
    lastModified: '2023-05-20',
    authorId: 'mock-user',
  },
  {
    id: 'CON-003',
    title: 'Marketing Services MSA',
    party: 'Creative Pulse Agency',
    value: 150000,
    currency: 'GHS',
    startDate: '2024-03-01',
    endDate: '2024-08-31',
    status: 'Review',
    category: 'Marketing',
    description: 'Master services agreement for digital marketing campaigns.',
    owner: 'Efua Addo',
    lastModified: '2024-03-15',
    authorId: 'mock-user',
  },
  {
    id: 'CON-004',
    title: 'Cloud Infrastructure Support',
    party: 'MTN Ghana',
    value: 280000,
    currency: 'GHS',
    startDate: '2023-11-01',
    endDate: '2024-10-31',
    status: 'Active',
    category: 'IT Services',
    description: '24/7 support for AWS and Azure environments.',
    owner: 'Abena Osei',
    lastModified: '2023-10-25',
    authorId: 'mock-user',
  },
  {
    id: 'CON-005',
    title: 'Consulting Agreement',
    party: 'Strategic Insights LLC',
    value: 50000,
    currency: 'GHS',
    startDate: '2024-02-01',
    endDate: '2024-04-30',
    status: 'Expired',
    category: 'Professional Services',
    description: 'Short-term strategic planning consulting.',
    owner: 'Kofi Boateng',
    lastModified: '2024-04-30',
    authorId: 'mock-user',
  },
];
